#!/usr/bin/env bash
set -e

hosts=(swarm-master load-balancer app-server-1 app-server-2 database)

for host in ${hosts[@]}; do
	eval $(docker-machine env ${host})
  docker run -d \
    --name=registrator \
    -h $(docker-machine ip ${host}) \
    -v=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:latest \
    consul://$(docker-machine ip consul):8500
done
